/* C extension for __rubex__common_utils_.
This file in generated by Rubex::Compiler. Do not change!
File generation time: 2018-05-22 19:18:16 +0200.*/

/*Header file for __rubex__common_utils_*/

#ifndef __rubex__COMMON_UTILS_H
#define __rubex__COMMON_UTILS_H
#include <ruby.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>


VALUE __rubex_char2rubystr(char ch);
#define __rubex_INT2BOOL(arg) (arg ? Qtrue : Qfalse)

#endif
