/* C extension for rubex_csv.
This file in generated by Rubex::Compiler. Do not change!
File generation time: 2018-05-22 19:18:16 +0200.*/

/*Code file for rubex_csv*/

#include "rubex_csv.h"
static void __rubex_c_f_NativeThreadReader_deallocate (void* __rubex_arg_raw_data)
{
  __rubex_t_NativeThreadReader_NativeThreadReader_data_struct* __rubex_ptr_data;
  __rubex_ptr_data = (__rubex_t_NativeThreadReader_NativeThreadReader_data_struct*)__rubex_arg_raw_data;

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:91 */
  fclose(__rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_file);

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:92 */
  xfree(__rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_data);

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:93 */
  xfree(__rubex_ptr_data[0].__rubex_ptr_csv_data);

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:95 */
  xfree(__rubex_ptr_data);
}

static size_t __rubex_c_f_NativeThreadReader_memcount (void* __rubex_arg_raw_data)
{
  return sizeof(__rubex_arg_raw_data);

}

static const rb_data_type_t __rubex_attach_rb_cls_NativeThreadReader_data_type_t = {
  "NativeThreadReader",
  {0, __rubex_c_f_NativeThreadReader_deallocate, __rubex_c_f_NativeThreadReader_memcount,
  0}, 0, 0, RUBY_TYPED_FREE_IMMEDIATELY
};

static __rubex_t_NativeThreadReader_NativeThreadReader_data_struct* __rubex_c_f_NativeThreadReader_get_struct (VALUE __rubex_arg_obj)
{
  __rubex_t_NativeThreadReader_NativeThreadReader_data_struct *data;
  
  TypedData_Get_Struct(__rubex_arg_obj, __rubex_t_NativeThreadReader_NativeThreadReader_data_struct, &__rubex_attach_rb_cls_NativeThreadReader_data_type_t, data);
  return data;
}

static VALUE __rubex_c_f_NativeThreadReader_allocate (VALUE __rubex_arg_self)
{
  __rubex_t_NativeThreadReader_NativeThreadReader_data_struct* __rubex_ptr_data;

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:95 */
  __rubex_ptr_data = (__rubex_t_NativeThreadReader_NativeThreadReader_data_struct*)xmalloc(sizeof(__rubex_t_NativeThreadReader_NativeThreadReader_data_struct));

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:95 */
  __rubex_ptr_data[0].__rubex_ptr_csv_data = (__rubex_t_Object_csv_data*)xmalloc(sizeof(__rubex_t_Object_csv_data));

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:86 */
  __rubex_ptr_data[0].__rubex_ptr_csv_data = (__rubex_t_Object_csv_data*)xmalloc(sizeof(__rubex_t_Object_csv_data));

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:87 */
  __rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_data = (char*)xmalloc(( ( sizeof(char) * 500000 ) * 200 ));
return TypedData_Wrap_Struct(__rubex_arg_self,&__rubex_attach_rb_cls_NativeThreadReader_data_type_t, __rubex_ptr_data);
}

static VALUE __rubex_c_f_no_gil_block_NativeThreadReader_read_and_profit_1 (void* global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_arg_dummy)
{

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:79 */
  global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_pr = __rubex_c_f_NativeThreadReader__read_and_profit(global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_line_no,( global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_step + global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_line_no ),global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_ptr_d);
}

static VALUE __rubex_rb_f_NativeThreadReader_initialize (int argc,VALUE* argv,VALUE __rubex_arg_self)
{
  VALUE __rubex_arg_file_name;
  VALUE __rubex_arg_lines;
  __rubex_t_NativeThreadReader_NativeThreadReader_data_struct* __rubex_ptr_data;
  char* __rubex_ptr_file;
  int __rubex_v_num_lines;
  int __rubex_v_i;
  VALUE __rubex_temp_1;
  if (argc < 2)
  {
    rb_raise(rb_eArgError, "Need 2 args, not %d", argc);
  }

  __rubex_arg_file_name=argv[0];
  __rubex_arg_lines=argv[1];
  __rubex_ptr_data = __rubex_c_f_NativeThreadReader_get_struct(__rubex_arg_self);

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:27 */
  rb_iv_set(__rubex_arg_self, "@file_name",  __rubex_arg_file_name);

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:28 */
  rb_iv_set(__rubex_arg_self, "@lines",  __rubex_arg_lines);
  __rubex_temp_1 = rb_iv_get(__rubex_arg_self, "@file_name");
  __rubex_ptr_file = StringValueCStr(__rubex_temp_1);
  __rubex_temp_1 = 0;
  __rubex_temp_1 = rb_iv_get(__rubex_arg_self, "@lines");
  __rubex_v_num_lines = NUM2INT(__rubex_temp_1);
  __rubex_temp_1 = 0;

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:32 */
  __rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_file = fopen(__rubex_ptr_file,"r");
  if (( __rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_file == NULL )) 
  {

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:33 */
    __rubex_temp_1 = rb_str_new2("Cannot read this file");
    __rubex_temp_1 = 0;
    rb_raise(rb_eArgError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));rb_raise(rb_eArgError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));;

  }

  __rubex_v_i = 0;
  while (( __rubex_v_i < __rubex_v_num_lines ))
  {

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:37 */
    fgets(&__rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_data[( __rubex_v_i * 200 )],200,__rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_file);

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:38 */
    __rubex_v_i = ( __rubex_v_i + 1 );
  }

}

static double __rubex_c_f_NativeThreadReader__read_and_profit (int __rubex_arg_line,int __rubex_arg_step,char* __rubex_arg_d)
{
  int __rubex_v_i;
  int __rubex_v_commas;
  int __rubex_v_j;
  char __rubex_v_c;
  char* __rubex_ptr_current_line;
  double __rubex_v_sum;
  __rubex_v_i = __rubex_arg_line;
  __rubex_v_sum = 0;
  while (( __rubex_v_i < __rubex_arg_step ))
  {

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:52 */
    __rubex_v_commas = 0;

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:53 */
    __rubex_v_j = 0;

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:54 */
    __rubex_ptr_current_line = &__rubex_arg_d[( __rubex_v_i * 200 )];
    while (( __rubex_v_commas < 13 ))
    {
      if (( __rubex_ptr_current_line[__rubex_v_j] == ',' )) 
      {

        /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:58 */
        __rubex_v_commas = ( __rubex_v_commas + 1 );

      }


      /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:60 */
      __rubex_v_j = ( __rubex_v_j + 1 );
    }


    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:62 */
    __rubex_v_sum = ( __rubex_v_sum + atoi(&__rubex_ptr_current_line[__rubex_v_j]) );

    /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:63 */
    __rubex_v_i = ( __rubex_v_i + 1 );
  }


  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:66 */
  return __rubex_v_sum;
}

static VALUE __rubex_rb_f_NativeThreadReader_read_and_profit (int argc,VALUE* argv,VALUE __rubex_arg_self)
{
  VALUE __rubex_arg_line;
  VALUE __rubex_arg_step_size;
  __rubex_t_NativeThreadReader_NativeThreadReader_data_struct* __rubex_ptr_data;
  if (argc < 2)
  {
    rb_raise(rb_eArgError, "Need 2 args, not %d", argc);
  }

  __rubex_arg_line=argv[0];
  __rubex_arg_step_size=argv[1];
  __rubex_ptr_data = __rubex_c_f_NativeThreadReader_get_struct(__rubex_arg_self);
  global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_line_no = NUM2INT(__rubex_arg_line);
  global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_step = NUM2INT(__rubex_arg_step_size);
  global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_pr = 0;
  global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_ptr_d = __rubex_ptr_data[0].__rubex_ptr_csv_data->__rubex_ptr_data;

  /* no_gil block: */

  /* Rubex file location:  */
  rb_thread_call_without_gvl(__rubex_c_f_no_gil_block_NativeThreadReader_read_and_profit_1, NULL, RUBY_UBF_PROCESS, NULL);

  /* Rubex file location: /Users/sameer/gitrepos/rubex_csv_reader/ext/rubex_csv/rubex_csv.rubex:82 */
  return rb_float_new(global_no_gil_block_NativeThreadReader_read_and_profit_1__rubex_v_pr);
}


void Init_rubex_csv ()
{
  __rubex_rb_cls_NativeThreadReader = rb_define_class("NativeThreadReader", rb_cObject);
  rb_define_alloc_func(__rubex_rb_cls_NativeThreadReader, __rubex_c_f_NativeThreadReader_allocate);

  rb_define_method(__rubex_rb_cls_NativeThreadReader ,"initialize", __rubex_rb_f_NativeThreadReader_initialize, -1);
  rb_define_method(__rubex_rb_cls_NativeThreadReader ,"read_and_profit", __rubex_rb_f_NativeThreadReader_read_and_profit, -1);
}

